---
  - hosts: node
    gather_facts: true
    become: false

    tasks:
      - name:
        ansible.builtin.debug:
          var: ansible_all_ipv4_addresses

      - name:
        ansible.builtin.debug:
          var: ansible_distribution

      - name:
        ansible.builtin.debug:
          var: ansible_os_family

      - name: 
        ansible.builtin.debug:
          var: ansible_default_ipv4.gateway

      - name: 
        ansible.builtin.debug:
          var: ansible_distribution_version