---
all:
  children:
    node:
      hosts:
        node01:
          ansible_host: 192.168.1.111
          ansible_user: ansible
          ansible_password: ansible
        node02:
          ansible_host: 192.168.1.112
          ansible_user: ansible
          ansible_password: ansible
