---
all:
  children:
    node: 
      hosts:
        node01:
          ansible_host: 192.168.1.111
        node02:
          ansible_host: 192.168.1.112
      vars:
        ansible_user: ansible
        ansible_ssh_private_key_file: /home/ansible/.ssh/id_rsa